### ISSUE TITLE
Dash in Grafana for ECS experiments 

### ISSUE THREAD

**Issue by thattommyhall** [ipfs-shipyard/thunderdome#15]
Should be able to go to a Grafana dash, select an experiment name and see all the targets and compare them in a few standard panes

- [x] add cloudwatch as a source in grafana
- [x] dash includes some cloudwatch metrics
- [x] dash includes some prom metrics

**Comment by JesseXie** [comment]
@thattommyhall is this done or still open, it be marked as done here: https://github.com/protocol/prodeng/issues/17
