### ISSUE TITLE
Add OTEL tracing to dealgood

### ISSUE THREAD

**Issue by thattommyhall** [ipfs-shipyard/thunderdome#18]
Should add correlation ID to each request (there is a task to add one for the prod gateways, we could move to use that w/o issue when it but I dont know how useful correlating with them is to us)

**Comment by iand** [comment]
I opened https://github.com/ipfs/kubo/issues/9168 but maybe there is an existing one?

**Comment by thattommyhall** [comment]
This is for Dealgood (trying to use tags, but maybe should have added it in the title too)

**Comment by iand** [comment]
Support OTEL_PROPAGATORS, see https://opentelemetry.io/docs/reference/specification/sdk-environment-variables/#general-sdk-configuration and go.opentelemetry.io/contrib/propagators/autoprop

**Comment by iand** [comment]
Added in https://github.com/ipfs-shipyard/thunderdome/commit/230a4540e39b65902dd0aad4c0c6faac2d70ecf1
