### ISSUE TITLE
Dealgood reports experiment level metrics

### ISSUE THREAD

**Issue by iand** [ipfs-shipyard/thunderdome#34]
Report rate, concurrency, duration and version of dealgood

**Comment by thattommyhall** [comment]
I'd like some stats about the timelyness of the stream too, how far behind `now()` we getting requests for

**Comment by iand** [comment]
Fixed by https://github.com/ipfs-shipyard/thunderdome/commit/58c2e165d90513326786ef7f225788cf7a40a53d
