### ISSUE TITLE
Make Dealgood resolve SRV records

### ISSUE THREAD

**Issue by thattommyhall** [ipfs-shipyard/thunderdome#46]
The bigger ECS tasks on EC2 instances end up with SRV records in place of A records (notionally they might be on various ports, but im sticking to 8080 and sizing them so there is one per VM)

Dealgood needs to resolve SRV where A do not exist, and will need to periodically refresh them in case the task is restarted and happens to land on another machine.

```
❯ dig SRV peering-big-with.thunder.dome +short
1 1 8080 c8382095b20e4954a6c72384efe70985.peering-big-with.thunder.dome.
```

**Comment by iand** [comment]
How frequently should we refresh them?

**Comment by iand** [comment]
Should dealgood resolve to IP+Port?

Thinking of doing thise: 

Lookup A record. If exists, use IP+port given in the target config
otherwise
Lookup SRV record. If exists, lookup IP of the service and use IP+service port

What  host header should be passed?

**Comment by thattommyhall** [comment]
We set a short TTL (see [here](https://github.com/ipfs-shipyard/thunderdome/blob/main/tf/modules/experiment/target.tf#L34)), and as we are using the new(ish) ECS / Route53 [Service Discovery](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-discovery.html) thing, I don't expect to hit trouble with DNS caching. Lots of folks will be relying on that discovery during autoscaling events, much more frequently than we have tasks go OOM. 
Refresh will only be needed if >2 tasks stopped at the same time and happened to get scheduled on different machines (with only one stopping it would just be rescheduled on the vacated machine), I think a 1min poll or maybe lookup again if the backend becomes unreachable?
