### ISSUE TITLE
Ensure targets cant fetch from each other

### ISSUE THREAD

**Issue by thattommyhall** [ipfs-shipyard/thunderdome#7]
needs #6 to be sure

**Comment by thattommyhall** [comment]
this is quite subtle, security groups can only have `allow` rules, but we can use [Network ACLS](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-network-acls.html) to prevent inbound access from the IPs of the deployed backends. A script could be triggered on a schedule to keep them up to date.

**Comment by thattommyhall** [comment]
Considering this done (via https://github.com/ipfs-shipyard/thunderdome/commit/700b79ce13c0a8c0ef36e22a1fa2231f11b253cd ) from the perspective of  https://github.com/protocol/prodeng/issues/16

**Comment by JesseXie** [comment]
@thattommyhall it is done or not?

**Comment by thattommyhall** [comment]
I'll make a new card with @iand's comments re: blocking in Kubo config, we've got [support](https://github.com/ipfs/kubo/issues/8492#issuecomment-1209822126) that it's useful (tests have same need to control where stuff is fetched from)

Confirmed with 

```
# ipfs swarm connect /p2p/12D3KooWJj76d91UfktyF9CfR1HxmjuV8DVAXMGUPTBPn4iAATDg
Error: connect 12D3KooWJj76d91UfktyF9CfR1HxmjuV8DVAXMGUPTBPn4iAATDg failure: routing: not found
```

uses all the routing methods available, so we are good for now, it's not impossible some new relaying or whatever will work around our network block (its kinda the point of libp2p isnt it?)

**Comment by thattommyhall** [comment]
tracking in https://github.com/ipfs-shipyard/thunderdome/issues/41
